language: rust
env:
  global:
    - secure: xvgEoA6Etp8KWAnA9FrCkPNTdz8dunFN93sgWFkd55NGtTqlLehHCvuqG/7DFteoQ6FK2+g45NqJoc2UWp1CUIs27Qm5ICvnmFFLSncHN2ofefN0fj0BWXJunVBuKsO1xYCossnXKsEBDSpLJ5BI1eMrJETyHW75Nb3YIXH0Dm4=
install:
  - sudo apt-get install libleveldb-dev
  - sudo apt-get install libsnappy-dev
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
rust:
  - nightly
sudo: required
